/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.util.Set;
import javax.swing.*;
import objects.*;

/**
 *
 * @author marco
 */
public class ShopPanel extends javax.swing.JFrame implements GUI {

    private final Warehouse warehouse;
    private Warehouse.Order order;

    /**
     * Creates new form ShopPanel
     */
    public ShopPanel(Warehouse warehouse) {
        initComponents();
        closeAllExcept(jPanelMenu);
        this.setResizable(false);
        this.warehouse = warehouse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButtonNewOrder = new javax.swing.JButton();
        jButtonHistoricalOrders = new javax.swing.JButton();
        jPanelAllOrders = new javax.swing.JPanel();
        jButtonBackAllOrders = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelNewOrder = new javax.swing.JPanel();
        jButtonEnd = new javax.swing.JButton();
        jButtonAddItems = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonBackShopPanel = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPaneInformations = new javax.swing.JScrollPane();
        jListInformations = new javax.swing.JList<>();
        jComboBoxCategoryArticle = new javax.swing.JComboBox<>();
        jComboBoxTypeArticle = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionale Negozio");
        setBounds(new java.awt.Rectangle(700, 200, 0, 0));

        jPanelMenu.setBackground(new java.awt.Color(93, 93, 93));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewOrder.setText("NUOVO ORDINE");
        jButtonNewOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewOrderActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonNewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, 100));

        jButtonHistoricalOrders.setText("STORICO ORDINI");
        jButtonHistoricalOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHistoricalOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoricalOrdersActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonHistoricalOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 200, 100));

        jPanelAllOrders.setBackground(new java.awt.Color(93, 93, 93));
        jPanelAllOrders.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelAllOrders.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelAllOrders.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelAllOrders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBackAllOrders.setText("INDIETRO");
        jButtonBackAllOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackAllOrdersActionPerformed(evt);
            }
        });
        jPanelAllOrders.add(jButtonBackAllOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 120, 40));
        jPanelAllOrders.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jPanelNewOrder.setBackground(new java.awt.Color(93, 93, 93));
        jPanelNewOrder.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelNewOrder.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelNewOrder.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelNewOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEnd.setText("FINE");
        jButtonEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEndActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jButtonEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 120, 40));

        jButtonAddItems.setText("AGGIUNGI ALTRI ARTICOLI");
        jButtonAddItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemsActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jButtonAddItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 230, 40));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("NUOVO ORDINE");
        jPanelNewOrder.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonBackShopPanel.setText("INDIETRO");
        jButtonBackShopPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackShopPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackShopPanelActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jButtonBackShopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 40));

        jLabel23.setForeground(new java.awt.Color(254, 254, 254));
        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Categoria Articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelNewOrder.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 80));

        jLabel24.setForeground(new java.awt.Color(254, 254, 254));
        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelNewOrder.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 560, 80));

        jListInformations.setModel(new DefaultListModel<String>());
        jScrollPaneInformations.setViewportView(jListInformations);

        jPanelNewOrder.add(jScrollPaneInformations, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 258, 560, 90));

        jComboBoxCategoryArticle.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));
        jComboBoxCategoryArticle.setSelectedItem(Sport.BASEBALL);
        jComboBoxCategoryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryArticleActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jComboBoxCategoryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        jComboBoxTypeArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeArticleActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jComboBoxTypeArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 520, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(1.0), "2",  new Integer(3)}
            },
            new String [] {
                "Prezzo", "data di produzione", "quantità"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanelNewOrder.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 560, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAllOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAllOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelNewOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOrderActionPerformed
        //apre il pannello nuovi ordini
        closeAllExcept(jPanelNewOrder);
    }//GEN-LAST:event_jButtonNewOrderActionPerformed

    private void jButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndActionPerformed
        saveInformation();

        //controllare correttezza info
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonEndActionPerformed

    private void jButtonAddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemsActionPerformed

        saveInformation();

        //controllare correttezza info
        //refresh del pannello

    }//GEN-LAST:event_jButtonAddItemsActionPerformed

    private void jButtonHistoricalOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoricalOrdersActionPerformed

        //apre il pannello dello storico degli ordini
        closeAllExcept(jPanelAllOrders);
    }//GEN-LAST:event_jButtonHistoricalOrdersActionPerformed

    private void jButtonBackShopPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackShopPanelActionPerformed

        //pulsante indietro: ritorna al menu
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackShopPanelActionPerformed

    private void jButtonBackAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackAllOrdersActionPerformed
        //pulsante indietro: ritorna al menu
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackAllOrdersActionPerformed

    private void jComboBoxCategoryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryArticleActionPerformed
        // rimuove tutti i tipi di articoli dal jComboBox
        jComboBoxTypeArticle.removeAllItems();

        // inserisce i tipi di articolo della categoria scelta:
        Set<String> articleTypes = warehouse.getArticleTypes(Sport.valueOf(jComboBoxCategoryArticle.getSelectedItem().toString()));
        articleTypes.forEach((String myString) -> {
            jComboBoxTypeArticle.addItem(myString);
        });
    }//GEN-LAST:event_jComboBoxCategoryArticleActionPerformed

    private void jComboBoxTypeArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeArticleActionPerformed
//        jListInformations.
        updateJList();
    }//GEN-LAST:event_jComboBoxTypeArticleActionPerformed

    private void updateJList() {
        jListInformations.removeAll();

        DefaultListModel model;
        model = new DefaultListModel<>();

        try {
            Set<String> articleTypes = warehouse.getArticleTypesInformation(Sport.valueOf(jComboBoxCategoryArticle.getSelectedItem().toString()), jComboBoxTypeArticle.getSelectedItem().toString());
            articleTypes.forEach((String myString) -> {
                model.addElement(myString);
            });

        } catch (NullPointerException e) {
            
        }
        

        
        jListInformations.setModel(model);
        jListInformations.setSelectedIndex(0);
    }

    //salva le informazioni inserite dall'utente
    public void saveInformation() {

        //salvataggio delle info dell'articolo in entrata
        String categoryArticle = jComboBoxCategoryArticle.getSelectedItem().toString();
        System.out.println("Categoria articolo: " + categoryArticle);

        //salvataggio del tipo di articolo
        String typeArticle = jComboBoxTypeArticle.getSelectedItem().toString();
        System.out.println("Tipo di articolo: " + typeArticle);

        //salvataggio del prezzo
//        String cost = jComboBoxCost.getSelectedItem().toString();
//        System.out.println("costo: " + cost);    
    }

    // rende visibile solo il pannello passato
    public void closeAllExcept(JPanel p) {
        jPanelAllOrders.setVisible(false);
        jPanelNewOrder.setVisible(false);
        jPanelMenu.setVisible(false);
        p.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddItems;
    private javax.swing.JButton jButtonBackAllOrders;
    private javax.swing.JButton jButtonBackShopPanel;
    private javax.swing.JButton jButtonEnd;
    private javax.swing.JButton jButtonHistoricalOrders;
    private javax.swing.JButton jButtonNewOrder;
    private javax.swing.JComboBox<objects.Sport> jComboBoxCategoryArticle;
    private javax.swing.JComboBox<String> jComboBoxTypeArticle;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListInformations;
    private javax.swing.JPanel jPanelAllOrders;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNewOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneInformations;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void whiteLabels(JPanel panel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void refreshPanel(JPanel panel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
