/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimarcolastversion;

import java.awt.Color;
import javax.swing.BorderFactory;
import objects.Sport;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import objects.*;

/**
 *
 * @author marco
 */
public class SecretaryPanel extends javax.swing.JFrame implements GUI {

    private final Warehouse warehouse;
    private Warehouse.Entry entry;

    /**
     * Creates new form SecretaryPanel
     */
    public SecretaryPanel(Warehouse warehouse) {
        initComponents();
        closeAllExcept(jPanelMenu);
        this.setResizable(false);
        this.warehouse = warehouse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButtonInsertNewArticle = new javax.swing.JButton();
        jButtonMovements = new javax.swing.JButton();
        jPanelShowAllMovement = new javax.swing.JPanel();
        jButtonBackEntryArticle1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelInesertNewArticle = new javax.swing.JPanel();
        jLabelInfoCode = new javax.swing.JLabel();
        jComboBoxCategoryArticle = new javax.swing.JComboBox<>();
        jTextFieldMaterials = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonBackEntryArticle = new javax.swing.JButton();
        jTextFieldNewArticleType = new javax.swing.JTextField();
        jLabelCategoryArticle = new javax.swing.JLabel();
        jLabelNewArticleType = new javax.swing.JLabel();
        jLabelMaterials = new javax.swing.JLabel();
        textAreaDescription = new java.awt.TextArea();
        jLabelDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionale Segreteria");
        setBounds(new java.awt.Rectangle(700, 200, 0, 0));

        jPanelMenu.setBackground(new java.awt.Color(93, 93, 93));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonInsertNewArticle.setText("INSERISCI NUOVO ARTICOLO");
        jButtonInsertNewArticle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsertNewArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertNewArticleActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonInsertNewArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 250, 80));

        jButtonMovements.setText("STORICO MOVIMENTI");
        jButtonMovements.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMovements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMovementsActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonMovements, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 250, 80));

        jPanelShowAllMovement.setBackground(new java.awt.Color(93, 93, 93));
        jPanelShowAllMovement.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelShowAllMovement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBackEntryArticle1.setText("INDIETRO");
        jButtonBackEntryArticle1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackEntryArticle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackEntryArticle1ActionPerformed(evt);
            }
        });
        jPanelShowAllMovement.add(jButtonBackEntryArticle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 40));

        jComboBox1.setModel(new DefaultComboBoxModel<>(objects.City.values()));
        jPanelShowAllMovement.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelShowAllMovement.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jPanelInesertNewArticle.setBackground(new java.awt.Color(93, 93, 93));
        jPanelInesertNewArticle.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelInesertNewArticle.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelInesertNewArticle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInfoCode.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabelInfoCode.setForeground(new java.awt.Color(254, 254, 254));
        jLabelInfoCode.setText("INSERIMENTO NUOVO ARTICOLO");
        jPanelInesertNewArticle.add(jLabelInfoCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 412, -1));

        jComboBoxCategoryArticle.setModel(new DefaultComboBoxModel<>(Sport.values()));
        jComboBoxCategoryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryArticleActionPerformed(evt);
            }
        });
        jPanelInesertNewArticle.add(jComboBoxCategoryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 510, 30));

        jTextFieldMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaterialsActionPerformed(evt);
            }
        });
        jPanelInesertNewArticle.add(jTextFieldMaterials, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 510, 30));

        jButtonSave.setText("SALVA");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanelInesertNewArticle.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 120, 40));

        jButtonBackEntryArticle.setText("INDIETRO");
        jButtonBackEntryArticle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackEntryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackEntryArticleActionPerformed(evt);
            }
        });
        jPanelInesertNewArticle.add(jButtonBackEntryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 40));
        jPanelInesertNewArticle.add(jTextFieldNewArticleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 510, 30));

        jLabelCategoryArticle.setForeground(new java.awt.Color(254, 254, 254));
        jLabelCategoryArticle.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Categoria Articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelInesertNewArticle.add(jLabelCategoryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 550, 80));

        jLabelNewArticleType.setForeground(new java.awt.Color(254, 254, 254));
        jLabelNewArticleType.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelInesertNewArticle.add(jLabelNewArticleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 550, 80));

        jLabelMaterials.setForeground(new java.awt.Color(254, 254, 254));
        jLabelMaterials.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Materiali utilizzati. Dividere con una virgola", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelInesertNewArticle.add(jLabelMaterials, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 550, 80));
        jPanelInesertNewArticle.add(textAreaDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 550, 130));

        jLabelDescription.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(254, 254, 254));
        jLabelDescription.setText("Descrizione");
        jPanelInesertNewArticle.add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelShowAllMovement, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelInesertNewArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelShowAllMovement, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelInesertNewArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertNewArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertNewArticleActionPerformed

        //Rende visibile il pannello Inserisci nuovo articolo
        closeAllExcept(jPanelInesertNewArticle);
    }//GEN-LAST:event_jButtonInsertNewArticleActionPerformed

    private void jButtonMovementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMovementsActionPerformed

        //Rende visibile il pannello visualizza movimenti articolo
        closeAllExcept(jPanelShowAllMovement);
    }//GEN-LAST:event_jButtonMovementsActionPerformed

    private void jComboBoxCategoryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoryArticleActionPerformed

    private void jTextFieldMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaterialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaterialsActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        saveInformationNewArticle();

        //controllare correttezza info

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonBackEntryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackEntryArticleActionPerformed

        // Pulsante indietro: torna alla schermata principale del magazzino
        closeAllExcept(jPanelMenu);
        whiteLabels(jPanelInesertNewArticle);
        refreshPanel(jPanelInesertNewArticle);
    }//GEN-LAST:event_jButtonBackEntryArticleActionPerformed

    private void jButtonBackEntryArticle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackEntryArticle1ActionPerformed

        // Apre il pannello menu
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackEntryArticle1ActionPerformed

    public void saveInformationNewArticle() {

        String typeArticle;
        String categoryArticle;
        String description;
        String material;

        boolean save = true;

        whiteLabels(jPanelInesertNewArticle);

        // Salvataggio delle info dell'articolo in entrata
        categoryArticle = jComboBoxCategoryArticle.getSelectedItem().toString();
        System.out.println("Categoria articolo: " + categoryArticle);

        // Salvataggio della descrizione
        description = textAreaDescription.getText();
        System.out.println("Descrizione: " + description);

        // Controllo che il label della descrizione non sia vuoto
        if (description.equals("")) {
            save = false;
            System.out.print("si");
            JOptionPane.showMessageDialog(null, "Inserire una descrizione!", "ATTENZIONE", JOptionPane.ERROR_MESSAGE);
        }

        // Salvataggio del tipo di articolo
        typeArticle = jTextFieldNewArticleType.getText();
        System.out.println("Tipo di articolo: " + typeArticle);

        // Controllo che il label tipo di articolo non sia vuoto
        if (typeArticle.equals("")) {
            save = false;
            jLabelNewArticleType.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        //salvataggio dei materiali
        material = jTextFieldMaterials.getText();
        System.out.println("materiali: " + material);

        // Controllo che il label dei materiali non sia vuoto
        if (material.equals("")) {
            save = false;
            jLabelMaterials.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio informazioni pulsanti della finestra di avviso
        if (save) {
            Object[] options = {"SI",
                "NO",
                "Aggiungi altri articoli"
            };

            /*
            * Finestra di avviso:
            * Vuoi Salvare?
            * 0 -> SI
            * 1 -> NO
            * 2 -> Aggiungi altri altricoli (salvataggio degli articoli e refresh della pagina)
             */
            int n = JOptionPane.showOptionDialog(null, "Vuoi salvare?", "", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);

            // n = 0 premuto pulsante SI
            if (n == 0) {

                // salvataggio del nuovo tipo di articolo
                warehouse.addArticleType(typeArticle, description, Sport.valueOf(categoryArticle), material);

                JOptionPane.showMessageDialog(null, "Salvato!");

                // si ritorna al menu del frame segreteria
                closeAllExcept(jPanelMenu);
                // refresh del pannello
                refreshPanel(jPanelInesertNewArticle);
                whiteLabels(jPanelInesertNewArticle);

                // DA CANCELLARE
                new WarehousePanel(warehouse).setVisible(true);

                // n = 1 premuto pulsante NO
            } else if (n == 1) {
                JOptionPane.showMessageDialog(null, "Operazione annullata");
                closeAllExcept(jPanelMenu);
                refreshPanel(jPanelInesertNewArticle);
                whiteLabels(jPanelInesertNewArticle);

                // n 0 2 premuto pulsante aggiungi articoli
            } else if (n == 2) {

                // salvataggio del nuovo tipo di articolo
                warehouse.addArticleType(typeArticle, description, Sport.valueOf(categoryArticle), material);
                JOptionPane.showMessageDialog(null, "Salvato!");

                // refresh del pannello
                refreshPanel(jPanelInesertNewArticle);
                whiteLabels(jPanelInesertNewArticle);
            }
        }
    }
    
    // Colora di bianco i bordi delle label del pannello passato
    public void whiteLabels(JPanel panel) {
        if (panel == jPanelInesertNewArticle) {
            jLabelMaterials.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Materiali utilizzati. Dividere con una virgola", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelNewArticleType.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }
    }

    // Refresh del pannello
    public void refreshPanel(JPanel panel) {

        if (panel == jPanelInesertNewArticle) {
            textAreaDescription.setText("");
            jTextFieldMaterials.setText("");
            jTextFieldNewArticleType.setText("");
        }

        if (panel == jPanelShowAllMovement) {

        }
    }

    // Rende visibile un pannello
    public void closeAllExcept(JPanel p) {
        jPanelMenu.setVisible(false);
        jPanelInesertNewArticle.setVisible(false);
        jPanelShowAllMovement.setVisible(false);
        p.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackEntryArticle;
    private javax.swing.JButton jButtonBackEntryArticle1;
    private javax.swing.JButton jButtonInsertNewArticle;
    private javax.swing.JButton jButtonMovements;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<City> jComboBox1;
    private javax.swing.JComboBox<Sport> jComboBoxCategoryArticle;
    private javax.swing.JLabel jLabelCategoryArticle;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelInfoCode;
    private javax.swing.JLabel jLabelMaterials;
    private javax.swing.JLabel jLabelNewArticleType;
    private javax.swing.JPanel jPanelInesertNewArticle;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelShowAllMovement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMaterials;
    private javax.swing.JTextField jTextFieldNewArticleType;
    private java.awt.TextArea textAreaDescription;
    // End of variables declaration//GEN-END:variables

}
