/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimarcolastversion;

import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import javax.swing.border.LineBorder;
import objects.*;

/**
 *
 * @author marco
 */
public class WarehousePanel extends javax.swing.JFrame implements GUI {

    private final Warehouse warehouse;
    private Warehouse.Entry entry;

    /**
     * Costruttore della classe.
     *
     * @param warehouse, magazzino
     */
    public WarehousePanel(Warehouse warehouse) {
        initComponents();
        closeAllExcept(jPanelMenu);
        this.setResizable(false);
        this.warehouse = warehouse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanelMenu = new javax.swing.JPanel();
        jButtonEntrataArticoli = new javax.swing.JButton();
        jButtonUscitaArticoli = new javax.swing.JButton();
        jButtonSpostamentoArticoli = new javax.swing.JButton();
        jPanelEntryArticle = new javax.swing.JPanel();
        jLabelInfoCode = new javax.swing.JLabel();
        jComboBoxCategoryArticle = new javax.swing.JComboBox<>();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldDay = new javax.swing.JTextField();
        jTextFieldMonth = new javax.swing.JTextField();
        jTextFieldYear = new javax.swing.JTextField();
        jButtonEntryPanelSave = new javax.swing.JButton();
        jComboBoxTypeArticle = new javax.swing.JComboBox<>();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldLevelEntry = new javax.swing.JTextField();
        jButtonBackEntryArticle = new javax.swing.JButton();
        jTextFieldShelfNumberEntry = new javax.swing.JTextField();
        jLabelEntryArticleCategory = new javax.swing.JLabel();
        jLabelEntryArticleType = new javax.swing.JLabel();
        jLabelEntryQuantity = new javax.swing.JLabel();
        jLabelEntryPrice = new javax.swing.JLabel();
        jLabelEntryProductionDate = new javax.swing.JLabel();
        jLabelEntryDay = new javax.swing.JLabel();
        jLabelEntryMonth = new javax.swing.JLabel();
        jLabelEntryYear = new javax.swing.JLabel();
        jLabelEntryWarehousePosition = new javax.swing.JLabel();
        jTextFieldRowEntry = new javax.swing.JTextField();
        jLabelEntryLevel = new javax.swing.JLabel();
        jLabelEntryRow = new javax.swing.JLabel();
        jLabelEntryShelgNumber = new javax.swing.JLabel();
        jPanelMoveArticle = new javax.swing.JPanel();
        jButtonBackMoveArticle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldMoveArticleLevel = new javax.swing.JTextField();
        jComboBoxMoveArticleCategoryArticle = new javax.swing.JComboBox<>();
        jTextFieldMoveArticleQuantity = new javax.swing.JTextField();
        jComboBoxMoveArticleTypeArticle = new javax.swing.JComboBox<>();
        jComboBoxMoveArticleCost = new javax.swing.JComboBox<>();
        jComboBoxMoveArticleThisPosition = new javax.swing.JComboBox<>();
        jTextFieldMoveArticleShelfNumber = new javax.swing.JTextField();
        jTextFieldMoveArticleRow = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelMoveArticleShelfNumber = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabelMoveArticleQuantity = new javax.swing.JLabel();
        jLabelMoveArticleRow = new javax.swing.JLabel();
        jLabelMoveArticleLevel = new javax.swing.JLabel();
        jPanelExitArticle = new javax.swing.JPanel();
        labelExitRow = new java.awt.Label();
        labelExitShelfNumber = new java.awt.Label();
        labelExitPrice1 = new java.awt.Label();
        labelExitArticleCategory = new java.awt.Label();
        labelExitLevel = new java.awt.Label();
        labelExitDay = new java.awt.Label();
        labelExitMonth = new java.awt.Label();
        labelExitYear = new java.awt.Label();
        labelExitPrice = new java.awt.Label();
        labelExitQuantity = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldForwarderName = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonBackExitArticle = new javax.swing.JButton();
        jLabelExitShopDestinationName = new javax.swing.JLabel();
        jComboBoxShopDestinationName = new javax.swing.JComboBox<>();
        jLabelExitOrderNumber = new javax.swing.JLabel();
        jComboBoxOrderNumber = new javax.swing.JComboBox<>();
        jLabelExitForwarderName = new javax.swing.JLabel();
        jLabelExitWarehousePosition1 = new javax.swing.JLabel();
        jLabelExitLevel = new javax.swing.JLabel();
        jLabelExitRow = new javax.swing.JLabel();
        jLabelExitShelfNumber = new javax.swing.JLabel();
        labelExitSlash = new java.awt.Label();
        labelExitSlash1 = new java.awt.Label();
        jLabelExitProductionDate = new javax.swing.JLabel();
        jLabelExitQuantity = new javax.swing.JLabel();
        jLabelExitPrice = new javax.swing.JLabel();
        jLabelExitArticleCategory = new javax.swing.JLabel();
        labelExitArticleType = new java.awt.Label();
        jLabelExitArticleType = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionale Magazzino");
        setBounds(new java.awt.Rectangle(700, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 600));

        jPanelMenu.setBackground(new java.awt.Color(93, 93, 93));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEntrataArticoli.setText("ENTRATA ARTICOLI");
        jButtonEntrataArticoli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEntrataArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrataArticoliActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonEntrataArticoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, 80));

        jButtonUscitaArticoli.setText("USCITA ARTICOLI");
        jButtonUscitaArticoli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUscitaArticoli.setMaximumSize(new java.awt.Dimension(115, 29));
        jButtonUscitaArticoli.setMinimumSize(new java.awt.Dimension(115, 29));
        jButtonUscitaArticoli.setPreferredSize(new java.awt.Dimension(115, 29));
        jButtonUscitaArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUscitaArticoliActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonUscitaArticoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, 80));

        jButtonSpostamentoArticoli.setText("SPOSTA ARTICOLI");
        jButtonSpostamentoArticoli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSpostamentoArticoli.setMaximumSize(new java.awt.Dimension(115, 29));
        jButtonSpostamentoArticoli.setMinimumSize(new java.awt.Dimension(115, 29));
        jButtonSpostamentoArticoli.setPreferredSize(new java.awt.Dimension(115, 29));
        jButtonSpostamentoArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpostamentoArticoliActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonSpostamentoArticoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 200, 80));

        jPanelEntryArticle.setBackground(new java.awt.Color(93, 93, 93));
        jPanelEntryArticle.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelEntryArticle.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelEntryArticle.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelEntryArticle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInfoCode.setForeground(new java.awt.Color(254, 254, 254));
        jLabelInfoCode.setText("Registrazione entrata articoli n. ");
        jPanelEntryArticle.add(jLabelInfoCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 23, 412, -1));

        jComboBoxCategoryArticle.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextFieldDay, org.jdesktop.beansbinding.ObjectProperty.create(), jComboBoxCategoryArticle, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxCategoryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryArticleActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jComboBoxCategoryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        jTextFieldQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 40, 30));

        jTextFieldDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDayActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 40, 30));
        jPanelEntryArticle.add(jTextFieldMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 40, 30));
        jPanelEntryArticle.add(jTextFieldYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 82, 30));

        jButtonEntryPanelSave.setText("SALVA");
        jButtonEntryPanelSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEntryPanelSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntryPanelSaveActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jButtonEntryPanelSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 130, 40));

        jComboBoxTypeArticle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTypeArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeArticleActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jComboBoxTypeArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 520, -1));

        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 40, 30));
        jPanelEntryArticle.add(jTextFieldLevelEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 40, 30));

        jButtonBackEntryArticle.setText("INDIETRO");
        jButtonBackEntryArticle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackEntryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackEntryArticleActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jButtonBackEntryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 40));

        jTextFieldShelfNumberEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldShelfNumberEntryActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldShelfNumberEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 40, 30));

        jLabelEntryArticleCategory.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryArticleCategory.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Categoria Articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryArticleCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 80));

        jLabelEntryArticleType.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryArticleType.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryArticleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 560, 80));

        jLabelEntryQuantity.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 80, 80));

        jLabelEntryPrice.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Prezzo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 80, 80));

        jLabelEntryProductionDate.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryProductionDate.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Data di produzione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryProductionDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 340, 130));

        jLabelEntryDay.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryDay.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Giorno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, 80));

        jLabelEntryMonth.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryMonth.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Mese", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, 80));

        jLabelEntryYear.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryYear.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Anno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 120, 80));

        jLabelEntryWarehousePosition.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryWarehousePosition.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Posizione in magazzino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryWarehousePosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 300, 130));

        jTextFieldRowEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRowEntryActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldRowEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 40, 30));

        jLabelEntryLevel.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 80, 80));

        jLabelEntryRow.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 80, 80));

        jLabelEntryShelgNumber.setForeground(new java.awt.Color(254, 254, 254));
        jLabelEntryShelgNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelEntryArticle.add(jLabelEntryShelgNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 80, 80));

        jPanelMoveArticle.setBackground(new java.awt.Color(93, 93, 93));
        jPanelMoveArticle.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelMoveArticle.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelMoveArticle.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelMoveArticle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBackMoveArticle.setText("INDIETRO");
        jButtonBackMoveArticle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackMoveArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackMoveArticleActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jButtonBackMoveArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 40));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("NUOVA POSIZIONE");
        jPanelMoveArticle.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 20));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("SPOSTA ARTICOLI");
        jPanelMoveArticle.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 20));

        jTextFieldMoveArticleLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoveArticleLevelActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldMoveArticleLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 40, 30));

        jComboBoxMoveArticleCategoryArticle.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));
        jComboBoxMoveArticleCategoryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMoveArticleCategoryArticleActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jComboBoxMoveArticleCategoryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        jTextFieldMoveArticleQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoveArticleQuantityActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldMoveArticleQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 40, 30));

        jComboBoxMoveArticleTypeArticle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COTOLETTA COL TONNO" }));
        jComboBoxMoveArticleTypeArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMoveArticleTypeArticleActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jComboBoxMoveArticleTypeArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 500, -1));

        jComboBoxMoveArticleCost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelMoveArticle.add(jComboBoxMoveArticleCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 120, -1));

        jComboBoxMoveArticleThisPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelMoveArticle.add(jComboBoxMoveArticleThisPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 500, -1));

        jTextFieldMoveArticleShelfNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoveArticleShelfNumberActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldMoveArticleShelfNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 40, 30));

        jTextFieldMoveArticleRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoveArticleRowActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldMoveArticleRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 40, 30));

        jButton1.setText("SALVA");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 120, 40));

        jLabelMoveArticleShelfNumber.setForeground(new java.awt.Color(254, 254, 254));
        jLabelMoveArticleShelfNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabelMoveArticleShelfNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 80, 80));

        jLabel32.setForeground(new java.awt.Color(254, 254, 254));
        jLabel32.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Prezzo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 160, 80));

        jLabel33.setForeground(new java.awt.Color(254, 254, 254));
        jLabel33.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Categoria Articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 80));

        jLabel34.setForeground(new java.awt.Color(254, 254, 254));
        jLabel34.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 540, 80));

        jLabel35.setForeground(new java.awt.Color(254, 254, 254));
        jLabel35.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Posizione attuale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 540, 80));

        jLabelMoveArticleQuantity.setForeground(new java.awt.Color(254, 254, 254));
        jLabelMoveArticleQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabelMoveArticleQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, 80));

        jLabelMoveArticleRow.setForeground(new java.awt.Color(254, 254, 254));
        jLabelMoveArticleRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabelMoveArticleRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 80, 80));

        jLabelMoveArticleLevel.setForeground(new java.awt.Color(254, 254, 254));
        jLabelMoveArticleLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelMoveArticle.add(jLabelMoveArticleLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 80, 80));

        jPanelExitArticle.setBackground(new java.awt.Color(93, 93, 93));
        jPanelExitArticle.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelExitArticle.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelExitArticle.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelExitArticle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelExitRow.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitRow.setForeground(new java.awt.Color(254, 254, 254));
        labelExitRow.setText("23");
        jPanelExitArticle.add(labelExitRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 30, 30));

        labelExitShelfNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitShelfNumber.setForeground(new java.awt.Color(254, 254, 254));
        labelExitShelfNumber.setText("23");
        jPanelExitArticle.add(labelExitShelfNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 30, 30));

        labelExitPrice1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitPrice1.setForeground(new java.awt.Color(254, 254, 254));
        labelExitPrice1.setText("Pagina 1 di 1");
        jPanelExitArticle.add(labelExitPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 30));

        labelExitArticleCategory.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitArticleCategory.setForeground(new java.awt.Color(254, 254, 254));
        labelExitArticleCategory.setText("PALLAVOLO");
        jPanelExitArticle.add(labelExitArticleCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 30));

        labelExitLevel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitLevel.setForeground(new java.awt.Color(254, 254, 254));
        labelExitLevel.setText("23");
        jPanelExitArticle.add(labelExitLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 30, 30));

        labelExitDay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitDay.setForeground(new java.awt.Color(254, 254, 254));
        labelExitDay.setText("23");
        jPanelExitArticle.add(labelExitDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 30, 30));

        labelExitMonth.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitMonth.setForeground(new java.awt.Color(254, 254, 254));
        labelExitMonth.setText("23");
        jPanelExitArticle.add(labelExitMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 30, 30));

        labelExitYear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitYear.setForeground(new java.awt.Color(254, 254, 254));
        labelExitYear.setText("2018");
        jPanelExitArticle.add(labelExitYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 50, 30));

        labelExitPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitPrice.setForeground(new java.awt.Color(254, 254, 254));
        labelExitPrice.setText("23");
        jPanelExitArticle.add(labelExitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 30, 30));

        labelExitQuantity.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitQuantity.setForeground(new java.awt.Color(254, 254, 254));
        labelExitQuantity.setText("23");
        jPanelExitArticle.add(labelExitQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 30, 30));

        jLabel6.setBackground(new java.awt.Color(254, 254, 254));
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Uscita articoli n.        in data");
        jPanelExitArticle.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextFieldForwarderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForwarderNameActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jTextFieldForwarderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 240, 30));

        jButtonSave.setText("SALVA");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.setMaximumSize(new java.awt.Dimension(80, 40));
        jButtonSave.setMinimumSize(new java.awt.Dimension(80, 40));
        jButtonSave.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 130, 40));

        jButtonBackExitArticle.setText("INDIETRO");
        jButtonBackExitArticle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackExitArticle.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonBackExitArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackExitArticleActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jButtonBackExitArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 40));

        jLabelExitShopDestinationName.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitShopDestinationName.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Negozio di destinazione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitShopDestinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 560, 80));

        jComboBoxShopDestinationName.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));
        jComboBoxShopDestinationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxShopDestinationNameActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jComboBoxShopDestinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 520, 30));

        jLabelExitOrderNumber.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitOrderNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Numero ordine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 80));

        jComboBoxOrderNumber.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));
        jComboBoxOrderNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrderNumberActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jComboBoxOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, 30));

        jLabelExitForwarderName.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitForwarderName.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Nome spedizioniere", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitForwarderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 280, 80));

        jLabelExitWarehousePosition1.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitWarehousePosition1.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Posizione in magazzino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitWarehousePosition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 280, 110));

        jLabelExitLevel.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 80, 60));

        jLabelExitRow.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 80, 60));

        jLabelExitShelfNumber.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitShelfNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitShelfNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 80, 60));

        labelExitSlash.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitSlash.setForeground(new java.awt.Color(254, 254, 254));
        labelExitSlash.setText("/");
        jPanelExitArticle.add(labelExitSlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 10, 30));

        labelExitSlash1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitSlash1.setForeground(new java.awt.Color(254, 254, 254));
        labelExitSlash1.setText("/");
        jPanelExitArticle.add(labelExitSlash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 10, 30));

        jLabelExitProductionDate.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitProductionDate.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Data di produzione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitProductionDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 160, 60));

        jLabelExitQuantity.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 80, 60));

        jLabelExitPrice.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Prezzo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 70, 60));

        jLabelExitArticleCategory.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitArticleCategory.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Categoria Articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitArticleCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 60));

        labelExitArticleType.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelExitArticleType.setForeground(new java.awt.Color(254, 254, 254));
        labelExitArticleType.setText("PALLA POCO TONDA");
        jPanelExitArticle.add(labelExitArticleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 300, 30));

        jLabelExitArticleType.setForeground(new java.awt.Color(254, 254, 254));
        jLabelExitArticleType.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.white), "Tipo di articolo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(254, 254, 254))); // NOI18N
        jPanelExitArticle.add(jLabelExitArticleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 330, 60));
        jPanelExitArticle.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEntryArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelExitArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMoveArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEntryArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelExitArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMoveArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDayActionPerformed

    private void jComboBoxCategoryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryArticleActionPerformed

        // rimuove tutti i tipi di articoli dal jComboBox
        jComboBoxTypeArticle.removeAllItems();

        // inserisce i tipi di articolo della categoria scelta:
        Set<String> articleTypes = warehouse.getAllArticleTypes(Sport.valueOf(jComboBoxCategoryArticle.getSelectedItem().toString()));
        articleTypes.forEach((String myString) -> {
            jComboBoxTypeArticle.addItem(myString);
        });
    }//GEN-LAST:event_jComboBoxCategoryArticleActionPerformed

    //rende visibile entrata articoli
    private void jButtonEntrataArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrataArticoliActionPerformed
        entry = warehouse.createEntry();
        //Rende visibile il pannello registra articoli
        closeAllExcept(jPanelEntryArticle);
    }//GEN-LAST:event_jButtonEntrataArticoliActionPerformed

    private void jButtonUscitaArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUscitaArticoliActionPerformed

        //Rende visibile il pannello uscita articoli
        closeAllExcept(jPanelExitArticle);
    }//GEN-LAST:event_jButtonUscitaArticoliActionPerformed

    //Salva tutte le informazioni dell'articolo quando viene premuto aggiungi altri articoli o fine
    private void jButtonEntryPanelSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntryPanelSaveActionPerformed

        saveInformationEntry();

        //refresh del pannello

    }//GEN-LAST:event_jButtonEntryPanelSaveActionPerformed

    private void jComboBoxTypeArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeArticleActionPerformed

    private void jTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantityActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldForwarderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForwarderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForwarderNameActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        saveInformationExit();

        //FARE CONTROLLO INFORMAZIONI

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonBackExitArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackExitArticleActionPerformed
        whiteLabels(jPanelExitArticle);
        refreshPanel(jPanelExitArticle);

        //pulsante indietro: torna alla schermata principale del magazzino
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackExitArticleActionPerformed

    private void jButtonBackEntryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackEntryArticleActionPerformed
        whiteLabels(jPanelEntryArticle);
        refreshPanel(jPanelEntryArticle);
        //pulsante indietro: torna alla schermata principale del magazzino
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackEntryArticleActionPerformed

    private void jButtonSpostamentoArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpostamentoArticoliActionPerformed

        //Rende visibile il pannello sposta articoli
        closeAllExcept(jPanelMoveArticle);
    }//GEN-LAST:event_jButtonSpostamentoArticoliActionPerformed

    private void jButtonBackMoveArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackMoveArticleActionPerformed
        whiteLabels(jPanelMoveArticle);
        refreshPanel(jPanelMoveArticle);
        //apre il pannello menu
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackMoveArticleActionPerformed

    private void jTextFieldMoveArticleLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoveArticleLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoveArticleLevelActionPerformed

    private void jTextFieldShelfNumberEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldShelfNumberEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShelfNumberEntryActionPerformed

    private void jComboBoxMoveArticleCategoryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMoveArticleCategoryArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMoveArticleCategoryArticleActionPerformed

    private void jTextFieldMoveArticleQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoveArticleQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoveArticleQuantityActionPerformed

    private void jComboBoxMoveArticleTypeArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMoveArticleTypeArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMoveArticleTypeArticleActionPerformed

    private void jTextFieldMoveArticleShelfNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoveArticleShelfNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoveArticleShelfNumberActionPerformed

    private void jTextFieldMoveArticleRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoveArticleRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoveArticleRowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //quando viene premuto il pulsante salva, salva la posizione di dove spostare gli articoli e la quantità
        saveInformationMove();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldRowEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRowEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRowEntryActionPerformed

    private void jComboBoxShopDestinationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxShopDestinationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxShopDestinationNameActionPerformed

    private void jComboBoxOrderNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrderNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrderNumberActionPerformed

    // Salvataggio delle informazioni degli articoli in entrata
    public void saveInformationEntry() {
        boolean save = true;

        whiteLabels(jPanelEntryArticle);

        // Salvataggio della categoria dell'articolo
        String categoryArticle = jComboBoxCategoryArticle.getSelectedItem().toString();
        System.out.println("Categoria articolo: " + categoryArticle);

        // Salvataggio del tipo di articolo
        String typeArticle = jComboBoxTypeArticle.getSelectedItem().toString();
        System.out.println("Tipo di articolo: " + typeArticle);

        // Salvataggio della quantità di articoli
        String quantity = jTextFieldQuantity.getText();
        System.out.println("quantità: " + quantity);

        // Controllo che le info inserite della quantità siano dei numeri e maggiori di zero
        try {
            int Nquantity = Integer.parseInt(quantity);
            if (Nquantity < 1) {
                save = false;
                jLabelEntryQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }
        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelEntryQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio della fila
        String row = jTextFieldRowEntry.getText();
        System.out.print("posizione: " + row);

        // Controllo che le info inserite della fila siano dei numeri e comprese tra 1 e 50
        try {
            int nRow = Integer.parseInt(row);
            if (nRow < 1 && nRow > 50) {
                save = false;
                jLabelEntryRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }

        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelEntryRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio dello scaffale
        String shelfNumber = jTextFieldShelfNumberEntry.getText();
        System.out.println(" " + shelfNumber);

        // Controllo che le info inserite dello scaffale siano dei numeri e comprese tra 1 e 50
        try {
            int nShelfNumber = Integer.parseInt(shelfNumber);
            if (nShelfNumber < 0 && nShelfNumber > 50) {
                save = false;
                jLabelEntryShelgNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }

        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelEntryShelgNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio del ripiano
        String level = jTextFieldLevelEntry.getText();
        System.out.println(" " + level);

        // Controllo che le info inserite del ripiano siano dei numeri e comprese tra 1 e 50
        try {
            int nLevel = Integer.parseInt(level);
            if (nLevel < 0 && nLevel > 50) {
                save = false;
                jLabelEntryLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }

        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelEntryLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio del prezzo
        String price = jTextFieldPrice.getText();
        System.out.println("Prezzo: " + price);

        try {
            int nPrice = Integer.parseInt(price);
            if (nPrice < 1) {
                save = false;
                jLabelEntryPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Prezzo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }

        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            jLabelEntryPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Prezzo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            save = false;
        }

        // Salvataggio del giorno
        String day = jTextFieldDay.getText();
        System.out.print("giorno: " + day);

        // Salvataggio del mese
        String month = jTextFieldMonth.getText();
        System.out.print(" " + month);

        // Salvataggio dell'anno
        String year = jTextFieldYear.getText();
        System.out.println(" " + year);

        // Controllo che giorno mese e anno siano dei numeri e controllo della veridicità della data
        try {
            int nDay = Integer.parseInt(day);
            int nMonth = Integer.parseInt(month);
            int nYear = Integer.parseInt(year);
            new MyDate(nYear, nMonth, nDay);
            new ProductionDate(nYear, nMonth, nDay);

        } catch (NumberFormatException e) {
            jLabelEntryProductionDate.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Data di produzione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            save = false;

        } catch (IllegalArgumentException e) {
            jLabelEntryProductionDate.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Data di produzione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            save = false;
        }

        // Salvataggio informazioni pulsanti della finestra di avviso
        if (save) {
            Object[] options = {"SI",
                "NO",
                "Aggiungi altri articoli"
            };

            /*
            * Finestra di avviso:
            * Vuoi Salvare?
            * 0 -> SI
            * 1 -> NO
            * 2 -> Aggiungi altri altricoli
             */
            int n = JOptionPane.showOptionDialog(null, "Vuoi salvare?", "", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);

            // n = 0 premuto pulsante SI
            if (n == 0) {
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                JOptionPane.showMessageDialog(null, "Salvato!");
                closeAllExcept(jPanelMenu);
                refreshPanel(jPanelEntryArticle);
                whiteLabels(jPanelEntryArticle);

                // n = 1 premuto pulsante NO
            } else if (n == 1) {
                JOptionPane.showMessageDialog(null, "Operazione annullata");
                closeAllExcept(jPanelMenu);
                refreshPanel(jPanelEntryArticle);
                whiteLabels(jPanelEntryArticle);

                // n = 2 premuto pulsante aggiungi articoli
            } else if (n == 2) {
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                refreshPanel(jPanelEntryArticle);
                whiteLabels(jPanelEntryArticle);
            }
        }

    }

    // Salvataggio delle info degli articoli in uscita
    public void saveInformationExit() {

        boolean save = true;

        whiteLabels(jPanelExitArticle);

        // Salvataggio del nome dello spedizioniere
        String forwarderName = jTextFieldForwarderName.getText();
        System.out.println("Nome spedizioniere: " + forwarderName);

        // Controllo che il label nome dello spedizioniere non sia vuoto
        if (forwarderName.equals("")) {
            save = false;
            jLabelExitForwarderName.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Nome spedizioniere", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio del nome del negozio di destinaione
        String shopDestinationName = jComboBoxShopDestinationName.getSelectedItem().toString();
        System.out.println("Negozio di destinazione: " + shopDestinationName);

        // Controllo che Negozio di destinazione non sia vuoto
        if (shopDestinationName.equals("")) {
            save = false;
            jLabelExitShopDestinationName.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Negozio di destinazione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // salvataggio del codice articolo
        String ArticleNumber = jComboBoxOrderNumber.getSelectedItem().toString();
        System.out.println("Numero dell'articolo: " + ArticleNumber);

        // Controllo che codice articolo non sia vuoto
        if (ArticleNumber.equals("")) {
            save = false;
            jLabelExitOrderNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Numero ordine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio informazioni pulsanti della finestra di avviso
        if (save) {
            Object[] options = {"SI",
                "NO",
                "Aggiungi altri articoli"
            };

            /*
            * Finestra di avviso:
            * Vuoi Salvare?
            * 0 -> SI
            * 1 -> NO
            * 2 -> Aggiungi altri altricoli (salvataggio degli articoli e refresh della pagina)
             */
            int n = JOptionPane.showOptionDialog(null, "Vuoi salvare?", "", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);

            // n = 0 premuto pulsante SI
            if (n == 0) {
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                JOptionPane.showMessageDialog(null, "Salvato!");
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                closeAllExcept(jPanelMenu);
                refreshPanel(jPanelExitArticle);
                whiteLabels(jPanelExitArticle);

                // n = 1 premuto pulsante NO
            } else if (n == 1) {
                JOptionPane.showMessageDialog(null, "Operazione annullata");
                closeAllExcept(jPanelMenu);
                refreshPanel(jPanelExitArticle);
                whiteLabels(jPanelExitArticle);

                // n 0 2 premuto pulsante aggiungi articoli
            } else if (n == 2) {
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                refreshPanel(jPanelExitArticle);
                whiteLabels(jPanelExitArticle);
            }
        }
    }

    // Salvataggio delle info degli articoli spostati
    public void saveInformationMove() {

        boolean save = true;

        // Imposto tutti i label bianchi
        whiteLabels(jPanelMoveArticle);

        // Salvataggio della quantità di articoli da spostare
        String quantity = jTextFieldMoveArticleQuantity.getText();
        System.out.println("quantità: " + quantity);

        // Controllo che le info inserite della quantità siano dei numeri e meaggiori di zero
        try {
            int Nquantity = Integer.parseInt(quantity);
            if (Nquantity < 1) {
                save = false;
                jLabelMoveArticleQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }
        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelMoveArticleQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio della fila
        String row = jTextFieldMoveArticleRow.getText();
        System.out.print("posizione: " + row);

        try {
            int nRow = Integer.parseInt(row);
            if (nRow < 1 && nRow > 50) {
                save = false;
                jLabelMoveArticleRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }

        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelMoveArticleRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio dello scaffale
        String shelfNumber = jTextFieldMoveArticleShelfNumber.getText();
        System.out.println(" " + shelfNumber);

        try {
            int nShelfNumber = Integer.parseInt(shelfNumber);
            if (nShelfNumber < 0 && nShelfNumber > 50) {
                save = false;
                jLabelMoveArticleShelfNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }

        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelMoveArticleShelfNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio del ripiano
        String level = jTextFieldMoveArticleLevel.getText();
        System.out.println(" " + level);

        try {
            int nLevel = Integer.parseInt(level);
            if (nLevel < 0 && nLevel > 50) {
                save = false;
                jLabelMoveArticleLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            }

        } catch (NumberFormatException e) {
            System.err.println("Caught IOException: " + e.getMessage());
            save = false;
            jLabelMoveArticleLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.RED), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        // Salvataggio informazioni pulsanti della finestra di avviso
        if (save) {

            Object[] options = {"SI",
                "NO",
                "Sposta altri articoli"
            };

            /*
            * Finestra di avviso:
            * Vuoi Salvare?
            * 0 -> SI
            * 1 -> NO
            * 2 -> Sposta altri altricoli (salvataggio degli articoli, refresh della pagina e labal di colore bianco)
             */
            int n = JOptionPane.showOptionDialog(null, "Vuoi salvare?", "", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);

            // n = 0 premuto pulsante SI
            if (n == 0) {
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                JOptionPane.showMessageDialog(null, "Salvato!");
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                closeAllExcept(jPanelMenu);
                refreshPanel(jPanelMoveArticle);
                whiteLabels(jPanelMoveArticle);

                // n = 1 premuto pulsante no
            } else if (n == 1) {
                JOptionPane.showMessageDialog(null, "Operazione annullata");
                closeAllExcept(jPanelMenu);
                refreshPanel(jPanelMoveArticle);
                whiteLabels(jPanelMoveArticle);

                // n = 2 premuto pulsante Sposta articoli
            } else if (n == 2) {
                //entry.addEnteredArticle(new ArticleInWarehouse(articleType, ERROR, ProductionDate, positionInWarehouse, SOMEBITS));
                refreshPanel(jPanelMoveArticle);
                whiteLabels(jPanelMoveArticle);
            }
        }
    }

    // Colora di bianco i bordi delle label del pannello passato
    public void whiteLabels(JPanel panel) {

        if (panel == jPanelEntryArticle) {
            jLabelEntryQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Quantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryProductionDate.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Data di produzione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Prezzo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryDay.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Giorno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryMonth.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Mese", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryYear.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Anno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Riga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryShelgNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelEntryLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        if (panel == jPanelExitArticle) {
            jLabelExitForwarderName.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Nome spedizioniere", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }

        if (panel == jPanelMoveArticle) {
            jLabelMoveArticleQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Qantità", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelMoveArticleRow.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Fila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelMoveArticleShelfNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Scaffale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
            jLabelMoveArticleLevel.setBorder(javax.swing.BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.WHITE), "Ripiano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255)));
        }
    }

    // Refresh del pannello
    public void refreshPanel(JPanel panel) {

        if (panel == jPanelEntryArticle) {
            jTextFieldQuantity.setText("");
            jTextFieldPrice.setText("");
            jTextFieldDay.setText("");
            jTextFieldMonth.setText("");
            jTextFieldYear.setText("");
            jTextFieldShelfNumberEntry.setText("");
            jTextFieldRowEntry.setText("");
            jTextFieldLevelEntry.setText("");
        }

        if (panel == jPanelExitArticle) {
            jTextFieldForwarderName.setText("");
        }

        if (panel == jPanelMoveArticle) {
            jTextFieldMoveArticleQuantity.setText("");
            jTextFieldMoveArticleRow.setText("");
            jTextFieldMoveArticleShelfNumber.setText("");
            jTextFieldMoveArticleLevel.setText("");
        }
    }

    // Visualizza solo il pannello passato
    public void closeAllExcept(JPanel p) {
        jPanelMenu.setVisible(false);
        jPanelExitArticle.setVisible(false);
        jPanelEntryArticle.setVisible(false);
        jPanelMoveArticle.setVisible(false);
        p.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBackEntryArticle;
    private javax.swing.JButton jButtonBackExitArticle;
    private javax.swing.JButton jButtonBackMoveArticle;
    private javax.swing.JButton jButtonEntrataArticoli;
    private javax.swing.JButton jButtonEntryPanelSave;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSpostamentoArticoli;
    private javax.swing.JButton jButtonUscitaArticoli;
    private javax.swing.JComboBox<objects.Sport> jComboBoxCategoryArticle;
    private javax.swing.JComboBox<objects.Sport> jComboBoxMoveArticleCategoryArticle;
    private javax.swing.JComboBox<String> jComboBoxMoveArticleCost;
    private javax.swing.JComboBox<String> jComboBoxMoveArticleThisPosition;
    private javax.swing.JComboBox<String> jComboBoxMoveArticleTypeArticle;
    private javax.swing.JComboBox<objects.Sport> jComboBoxOrderNumber;
    private javax.swing.JComboBox<objects.Sport> jComboBoxShopDestinationName;
    private javax.swing.JComboBox<String> jComboBoxTypeArticle;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEntryArticleCategory;
    private javax.swing.JLabel jLabelEntryArticleType;
    private javax.swing.JLabel jLabelEntryDay;
    private javax.swing.JLabel jLabelEntryLevel;
    private javax.swing.JLabel jLabelEntryMonth;
    private javax.swing.JLabel jLabelEntryPrice;
    private javax.swing.JLabel jLabelEntryProductionDate;
    private javax.swing.JLabel jLabelEntryQuantity;
    private javax.swing.JLabel jLabelEntryRow;
    private javax.swing.JLabel jLabelEntryShelgNumber;
    private javax.swing.JLabel jLabelEntryWarehousePosition;
    private javax.swing.JLabel jLabelEntryYear;
    private javax.swing.JLabel jLabelExitArticleCategory;
    private javax.swing.JLabel jLabelExitArticleType;
    private javax.swing.JLabel jLabelExitForwarderName;
    private javax.swing.JLabel jLabelExitLevel;
    private javax.swing.JLabel jLabelExitOrderNumber;
    private javax.swing.JLabel jLabelExitPrice;
    private javax.swing.JLabel jLabelExitProductionDate;
    private javax.swing.JLabel jLabelExitQuantity;
    private javax.swing.JLabel jLabelExitRow;
    private javax.swing.JLabel jLabelExitShelfNumber;
    private javax.swing.JLabel jLabelExitShopDestinationName;
    private javax.swing.JLabel jLabelExitWarehousePosition1;
    private javax.swing.JLabel jLabelInfoCode;
    private javax.swing.JLabel jLabelMoveArticleLevel;
    private javax.swing.JLabel jLabelMoveArticleQuantity;
    private javax.swing.JLabel jLabelMoveArticleRow;
    private javax.swing.JLabel jLabelMoveArticleShelfNumber;
    private javax.swing.JPanel jPanelEntryArticle;
    private javax.swing.JPanel jPanelExitArticle;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMoveArticle;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldForwarderName;
    private javax.swing.JTextField jTextFieldLevelEntry;
    private javax.swing.JTextField jTextFieldMonth;
    private javax.swing.JTextField jTextFieldMoveArticleLevel;
    private javax.swing.JTextField jTextFieldMoveArticleQuantity;
    private javax.swing.JTextField jTextFieldMoveArticleRow;
    private javax.swing.JTextField jTextFieldMoveArticleShelfNumber;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldRowEntry;
    private javax.swing.JTextField jTextFieldShelfNumberEntry;
    private javax.swing.JTextField jTextFieldYear;
    private java.awt.Label labelExitArticleCategory;
    private java.awt.Label labelExitArticleType;
    private java.awt.Label labelExitDay;
    private java.awt.Label labelExitLevel;
    private java.awt.Label labelExitMonth;
    private java.awt.Label labelExitPrice;
    private java.awt.Label labelExitPrice1;
    private java.awt.Label labelExitQuantity;
    private java.awt.Label labelExitRow;
    private java.awt.Label labelExitShelfNumber;
    private java.awt.Label labelExitSlash;
    private java.awt.Label labelExitSlash1;
    private java.awt.Label labelExitYear;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
